apiVersion: v1
kind: Service
metadata:
  name: trystack-service
spec:
  type: NodePort
  selector:
    app: trystack
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trystack
  labels:
    app: trystack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trystack
  template:
    metadata:
      labels:
        app: trystack
  spec:
    containers:
      - name: trystack
        image: razzaghib/trystack:latest
        ports:
          - containerPort: 5000

