from trystack.trystack import db
from trystack.util import uuidgen, now

class Order(db.Model):
    id=db.Column(db.String(64),primary_key=True,default=uuidgen)
    sessionId=db.Column(db.String(100))
    token=db.Column(db.String(100))
    status=db.Column(db.SmallInteger())
    subTotal=db.Column(db.Float())
    itemDiscount=db.Column(db.Float())
    tax=db.Column(db.Float())
    shipping=db.Column(db.Float())
    total=db.Column(db.Float())
    promo=db.Column(db.String(1000))
    discount=db.Column(db.Float())
    grandTotal=db.Column(db.Float())
    firstname=db.Column(db.String(100))
    middilename=db.Column(db.String(100))
    lastname=db.Column(db.Sting(100))
    mobile=db.Column(db.String(100))
    email=db.Column(db.String(100))
    line1=db.Column(db.String(100))
    line2=db.Column(db.String(100))
    city=db.Column(db.String(100))
    provience=db.Column(db.String(100))
    country=db.Column(db.String(100))
    createdat=db.Column(db.DateTime(),default=now)
    updatedat=db.Column(db.DateTime())
    content=db.Column(db.String(100))
    userId=db.Column(db.String(64),db.ForeignKey("user.id"))