"""create tag relationship

Revision ID: 317d6fc4fb0f
Revises: f80e788f721e
Create Date: 2023-02-13 14:19:04.145325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317d6fc4fb0f'
down_revision = 'f80e788f721e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=75), nullable=False),
    sa.Column('metaTitle', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tag_id')

    op.drop_table('tag')
    # ### end Alembic commands ###
