"""create product tbl

Revision ID: 3238a6d91c6c
Revises: 5904596f99bc
Create Date: 2023-02-13 12:49:12.867982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3238a6d91c6c'
down_revision = '5904596f99bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('userId', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('metaTile', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('price', sa.String(length=64), nullable=False),
    sa.Column('discount', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updateAt', sa.DateTime(), nullable=True),
    sa.Column('publishedAt', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
