"""create category dbl new fields

Revision ID: 4a274462fdc6
Revises: 22d0658781fb
Create Date: 2023-02-13 11:41:27.988649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a274462fdc6'
down_revision = '22d0658781fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=75), nullable=False))
        batch_op.add_column(sa.Column('metaTitle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('slug')
        batch_op.drop_column('metaTitle')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
