"""create category dbl new fields

Revision ID: 5904596f99bc
Revises: 4a274462fdc6
Create Date: 2023-02-13 12:33:38.405097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5904596f99bc'
down_revision = '4a274462fdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_category',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_category')
    # ### end Alembic commands ###
