"""create tag tbl and product tag tbl with relationship

Revision ID: 718bdb7c3997
Revises: 9b0eb6007772
Create Date: 2023-02-13 14:00:34.362371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '718bdb7c3997'
down_revision = '9b0eb6007772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_category',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('category_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='project_category_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='project_category_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('product_category')
    # ### end Alembic commands ###
