"""chnage datetime default

Revision ID: 77b73cecca60
Revises: 8888a9f33523
Create Date: 2023-01-01 19:03:50.990878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77b73cecca60'
down_revision = '8888a9f33523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('registeredAt',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('registeredAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
