"""create product tbl with category relationship

Revision ID: 9b0eb6007772
Revises: 3238a6d91c6c
Create Date: 2023-02-13 12:57:45.472709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0eb6007772'
down_revision = '3238a6d91c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
