"""create tag tbl and product tag tbl with relationship

Revision ID: b13e4ace5779
Revises: 718bdb7c3997
Create Date: 2023-02-13 14:11:02.036077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b13e4ace5779'
down_revision = '718bdb7c3997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_constraint('product_category_ibfk_1', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.VARCHAR(length=64), nullable=True))
        batch_op.create_foreign_key('product_category_ibfk_1', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###
